name: Export source

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: udiscord-source
          path: |
            .
            !.git
          include-hidden-files: true
          retention-days: 1
